[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"
 
[sepolia.address]
registry = 0x86EFBD0b6736Bed994962f9797049422A3A8E8Ad
poolManager = 0xE03A1074c86CFeDd5C142C4F04F1a1536e203543
positionManager = 0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4
router = 0x3A9D48AB9751398BbFa63ad67599Bb04e4BdF98b
stateView = 0xE1Dd9c3fA50EDB962E442f60DfBc432e24537E4C
permit2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3
quoter = 0x61B3f2011A92d183C7dbaDBdA940a7555Ccf9227
admin = 0xB3FFde53f0076295f2C183f13b4A07dE288Df61D
