[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"

[sepolia.address]
registry = "0x86EFBD0b6736Bed994962f9797049422A3A8E8Ad"
poolManager = "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543"
positionManager = "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4"
router = "0x3A9D48AB9751398BbFa63ad67599Bb04e4BdF98b"
stateView = "0xE1Dd9c3fA50EDB962E442f60DfBc432e24537E4C"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
quoter = "0x61B3f2011A92d183C7dbaDBdA940a7555Ccf9227"
admin = "0xB3FFde53f0076295f2C183f13b4A07dE288Df61D"
usdc = "0xeFaB8a965cD21077C9A8781dFc4D21825B76F29E"
donationWalletBeacon = "0xf45b2E67c5E5b0c4dFa1C8a4c2b45F0f3837CbC0"
donationWalletImplementation = "0xE481a932694DeE88912f285FA8c22980aB4c2673"
treasuryWalletBeacon = "0xb9419c81CD115c77026F21a0c7D9789d41220792"
treasuryWalletImplementation = "0x667594f49f23ce72678a0515fAE4f7b01661808C"
factoryImplementation = "0x25016e98BF8f6641e5cADEaa2FDf00517C31592E"
factory = "0x18438EaCad0a229cFB642d6257316ea65BF3bEfb"
